#!/usr/bin/env bash

export COMPlus_ZapDisable=1
export COMPlus_ReadyToRun=0

export SSL_CERT_FILE=/usr/local/share/certs/ca-root-nss.crt
export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0

export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1

dotnet %%PREFIX%%/lib/powershell/pwsh.dll "$@"
